Repository Solaestas/Everglow, pull requests merged in 2023-07, with the labels that each got.

#192 修改为nuget，但是仍有bug
  Documents/源代码编译流程.md
  Everglow.sln
  Sources/Directory.Build.props
  Sources/Directory.Build.targets
  Sources/Everglow.Core/Everglow.Core.csproj
  Sources/Everglow.Function/Everglow.Function.csproj
  Sources/Everglow.Function/FeatureFlags/DebugModeNotes.md
  Sources/Everglow.Scripts/Completer.cs
  Sources/Everglow.Scripts/Everglow.Scripts.csproj
  Sources/Everglow.Scripts/Module.cs
  Sources/Everglow.Scripts/Program.cs
  Sources/Everglow.Scripts/Script.cs
  Sources/Everglow.Scripts/Usings.cs
  Sources/Everglow.Scripts/Utils.cs
  Sources/Everglow/Everglow.csproj
  Sources/Everglow/Everglow.targets
  Sources/Everglow/Libraries/SubworldLibrary.dll
  Sources/Everglow/Libraries/SubworldLibrary.xml
  Sources/Everglow/Module.Build.props
  Sources/ManageModule.sh
  Sources/Modules/AssetReplace/Everglow.AssetReplace.csproj
  Sources/Modules/CagedDomain/Everglow.CagedDomain.csproj
  Sources/Modules/Directory.Build.props
  Sources/Modules/EternalResolve/Everglow.EternalResolve.csproj
  Sources/Modules/Example/Everglow.Example.csproj
  Sources/Modules/Food/Everglow.Food.csproj
  Sources/Modules/MEAC/Everglow.MEAC.csproj
  Sources/Modules/Minortopography/Everglow.Minortopography.csproj
  Sources/Modules/Module.props
  Sources/Modules/Myth/Everglow.Myth.csproj
  Sources/Modules/Ocean/Everglow.Ocean.csproj
  Sources/Modules/Plant/Everglow.Plant.csproj
  Sources/Modules/PlantAndFarm/Everglow.PlantAndFarm.csproj
  Sources/Modules/TwilightForest/Everglow.TwilightForest.csproj
  Sources/Modules/Yggdrasil/Everglow.Yggdrasil.csproj
  Sources/Modules/ZY/Everglow.ZY.csproj
  Sources/Shared.targets
Labels: needs further testing

#203 Cyfrost Blade Adjustments
  Sources/Modules/Myth/Misc/Items/Weapons/CyanFrost.cs
  Sources/Modules/Myth/Misc/Projectiles/Weapon/Melee/CyanFrostProj.cs
  Sources/Modules/Myth/Misc/Projectiles/Weapon/Melee/CyanFrostProj.png
Labels: enhancement

#199 Developer Name Secret System
  Sources/Everglow.Function/Utilities/PlayerUtils.cs
  Sources/Modules/Myth/TheFirefly/NPCs/Bosses/EvilPack.cs
Labels: enhancement, needs further testing

#207 Fix Bugs
  Sources/Modules/MEAC/Items/VortexVanquisherItem.cs
  Sources/Modules/Myth/Misc/Items/Weapons/Hepuyuan.cs
  Sources/Modules/Myth/TheFirefly/Projectiles/BlueMissilFriendly.png
  Sources/Modules/Myth/TheFirefly/Projectiles/ButterflyDreamFriendly.cs
  Sources/Modules/Myth/TheFirefly/Projectiles/ScaleWingBladeProj.cs
  Sources/Modules/PlantAndFarm/Items/Accessories/ThreeColorCrown.cs
  Sources/Modules/PlantAndFarm/Items/Materials/FlowerBrochure.cs
  Sources/Modules/PlantAndFarm/Items/Materials/PAFGlobalTile.cs
  Sources/Modules/PlantAndFarm/Items/Materials/PAFPlayer.cs
Labels: enhancement
